server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # API Application Logs
  - job_name: api-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-boilerplate
          host: api-boilerplate
          component: app
          __path__: /var/log/api/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            time: time
            component: component
            msg: msg
            correlationId: correlationId
            method: method
            path: path
            statusCode: statusCode
            duration: duration
            userId: userId
            email: email
            userAgent: userAgent
            ip: ip
      - labels:
          level:
          component:
          method:
          path:
      - timestamp:
          source: time
          format: RFC3339

  # API Error Logs
  - job_name: api-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-boilerplate
          host: api-boilerplate
          component: error
          __path__: /var/log/api/error.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            time: time
            component: component
            msg: msg
            err: err
            correlationId: correlationId
            userId: userId
      - labels:
          level:
          component:
      - timestamp:
          source: time
          format: RFC3339

  # API Access Logs  
  - job_name: api-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-boilerplate
          host: api-boilerplate
          component: access
          __path__: /var/log/api/access.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            time: time
            component: component
            msg: msg
            correlationId: correlationId
            method: method
            path: path
            statusCode: statusCode
            duration: duration
            userAgent: userAgent
            ip: ip
            type: type
      - labels:
          level:
          component:
          method:
          path:
          type:
      - timestamp:
          source: time
          format: RFC3339

  # Docker Container Logs (optional - for when API runs in Docker)
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/api-boilerplate-(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_name']
        regex: '/api-boilerplate-(.*)'
        target_label: 'job'
        replacement: 'api-boilerplate-${1}'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - json:
          expressions:
            level: level
            time: time
            component: component
            msg: msg
      - labels:
          level:
          component:
          stream:
      - timestamp:
          source: time
          format: RFC3339
          fallback_formats:
            - RFC3339Nano
            - "2006-01-02T15:04:05.000Z07:00"
