apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-datasource
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki-datasource
          matcherRegex: '"correlationId":"([^"]*)"'
          name: "Correlation ID"
          url: '/explore?orgId=1&left={"datasource":"loki-datasource","queries":[{"expr":"{job=\"api-boilerplate\"} |~ \"correlationId\\\":\\\"${__value.raw}\\\"\"","refId":"A"}],"range":{"from":"now-1h","to":"now"}}'
        - datasourceUid: loki-datasource
          matcherRegex: '"userId":"([^"]*)"'
          name: "User ID"
          url: '/explore?orgId=1&left={"datasource":"loki-datasource","queries":[{"expr":"{job=\"api-boilerplate\"} |~ \"userId\\\":\\\"${__value.raw}\\\"\"","refId":"A"}],"range":{"from":"now-1h","to":"now"}}'
